"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { ArrowRight, CheckCircle, HouseLine, MapPin, UserCircle } from "@phosphor-icons/react";
import { ArticleContentRenderer } from "./article-content-renderer";
import type { ArtigoBlock } from "@/lib/artigos/content";
import type { LandingPageBlock, LandingPageContent, LandingPageFormField } from "@/lib/landing-pages/content";
import { getBrowserAttributionContext, trackPublicEvent } from "@/lib/marketing/browser-attribution";
import { getAccessToken } from "@/lib/client/auth-api";

type Props = { pageId: string; nickname: string; brokerName: string; avatarUrl: string | null; creci: string; content: LandingPageContent };
const ARTICLE_TYPES = new Set(["paragraph","heading","quote","list","image","gallery","youtube","cta","button","property_feature","property_carousel"]);

export function LandingPagePublic({ pageId, nickname, brokerName, avatarUrl, creci, content }: Props) {
  useEffect(() => { void track(pageId,"VIEW"); }, [pageId]);
  return <main className="min-h-screen bg-white text-slate-950">{content.blocks.map((block) => <LandingBlock key={block.id} block={block} pageId={pageId} nickname={nickname} brokerName={brokerName} avatarUrl={avatarUrl} creci={creci}/>)}</main>;
}

function LandingBlock(props: Omit<Props,"content"> & { block: LandingPageBlock }) {
  const { block, pageId, nickname, brokerName, avatarUrl, creci } = props;
  if (ARTICLE_TYPES.has(block.type)) return <section className="px-5 py-12"><ArticleContentRenderer content={{ version:1, blocks:[block as ArtigoBlock] }} nickname={nickname} brokerName={brokerName} avatarUrl={avatarUrl} creci={creci}/></section>;
  if (block.type === "hero") {
    const d = block.data;
    const height = d.height === "screen" ? "min-h-screen" : d.height === "normal" ? "min-h-[520px]" : "min-h-[680px]";
    const hasImage = Boolean(d.imageUrl);
    return <section className={`relative flex ${height} items-center justify-center overflow-hidden px-5 py-24 text-center ${hasImage ? "text-white" : "bg-white text-slate-950"}`} style={hasImage ? { backgroundImage:`url(${d.imageUrl})`, backgroundPosition:"center", backgroundSize:"cover", backgroundAttachment:d.parallax?"fixed":"scroll" } : undefined}>{hasImage?<div className="absolute inset-0 bg-slate-950" style={{opacity:d.overlay/100}}/>:null}<div className="relative flex w-full max-w-5xl flex-col items-center"><p className={`mb-4 text-xs font-bold uppercase tracking-[.25em] ${hasImage?"text-[#c9c1a7]":"text-[var(--grey-olive)]"}`}>{brokerName} · {creci}</p><h1 className="max-w-5xl text-4xl font-light leading-tight md:text-7xl">{d.title}</h1>{d.subtitle?<p className={`mt-6 max-w-2xl text-lg font-light leading-8 md:text-xl ${hasImage?"text-white/80":"text-slate-500"}`}>{d.subtitle}</p>:null}<a href="#formulario" onClick={()=>void track(pageId,"CTA_CLICK",{block_id:block.id})} className={`mt-9 inline-flex items-center gap-3 rounded-xl px-6 py-3.5 font-bold shadow-xl ${hasImage?"bg-white text-slate-950":"bg-slate-950 text-white"}`}>{d.buttonLabel}<ArrowRight/></a></div></section>;
  }
  if(block.type==="split_media"){const d=block.data;const media=d.mediaUrl?(d.mediaType==="image"?<div className="relative min-h-[360px] overflow-hidden rounded-2xl"><Image src={d.mediaUrl} alt={d.title} fill className="object-cover" unoptimized/></div>:<iframe src={youtubeEmbed(d.mediaUrl)} title={d.title} className="aspect-video w-full rounded-2xl" allowFullScreen/>):<div className="min-h-[360px] rounded-2xl bg-stone-100"/>;const copy=<div className="flex flex-col justify-center"><h2 className="text-3xl font-light md:text-5xl">{d.title}</h2>{d.subtitle?<p className="mt-3 text-lg text-slate-500">{d.subtitle}</p>:null}<div className="article-rich-text mt-6 leading-8 text-slate-600" dangerouslySetInnerHTML={{__html:d.content}}/>{d.buttonLabel?<a href="#formulario" className="mt-6 inline-flex w-fit rounded-lg bg-slate-950 px-5 py-3 font-bold text-white">{d.buttonLabel}</a>:null}</div>;return <section className="px-5 py-16"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-2">{d.mediaSide==="left"?<>{media}{copy}</>:<>{copy}{media}</>}</div></section>;}
  if(block.type==="benefits"){return <section className="bg-stone-50 px-5 py-16"><div className="mx-auto max-w-7xl"><h2 className="text-center text-3xl font-light md:text-5xl">{block.data.title}</h2>{block.data.subtitle?<p className="mx-auto mt-4 max-w-2xl text-center text-slate-500">{block.data.subtitle}</p>:null}<div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{block.data.items.map((item,index)=><article key={`${item.title}-${index}`} className="rounded-2xl border border-stone-200 bg-white p-6 shadow-sm"><CheckCircle size={28} className="text-[var(--grey-olive)]"/><h3 className="mt-4 text-xl font-medium">{item.title}</h3><p className="mt-2 leading-7 text-slate-500">{item.description}</p></article>)}</div></div></section>;}
  if(block.type==="lead_form") return <LandingForm pageId={pageId} blockId={block.id} data={block.data}/>;
  if(block.type==="faq") return <section className="px-5 py-16"><div className="mx-auto max-w-4xl"><h2 className="text-3xl font-light md:text-5xl">{block.data.title}</h2><div className="mt-8 divide-y divide-stone-200">{block.data.items.map((item,index)=><details key={`${item.question}-${index}`} className="group py-5"><summary className="cursor-pointer list-none text-lg font-medium">{item.question}</summary><p className="mt-3 leading-7 text-slate-500">{item.answer}</p></details>)}</div></div></section>;
  if(block.type==="broker_profile") return <section className="bg-slate-950 px-5 py-16 text-white"><div className="mx-auto flex max-w-4xl flex-col items-center text-center">{avatarUrl?<Image src={avatarUrl} alt={brokerName} width={112} height={112} className="h-28 w-28 rounded-full object-cover" unoptimized/>:<UserCircle size={112} className="text-white/40"/>}<h2 className="mt-5 text-3xl font-light">{brokerName}</h2><p className="mt-2 text-sm uppercase tracking-widest text-[#c9c1a7]">{creci}</p><Link href={`/${nickname}`} className="mt-6 rounded-lg border border-white/30 px-5 py-3 text-sm font-bold">Conhecer meu perfil</Link></div></section>;
  if(block.type==="location") return <section className="px-5 py-16"><div className="mx-auto max-w-7xl rounded-2xl bg-stone-100 p-8"><MapPin size={32}/><h2 className="mt-4 text-3xl font-light">Localização</h2><p className="mt-3 text-slate-500">{String(block.data.address??"Consulte a localização com o corretor.")}</p></div></section>;
  if(block.type==="social_proof") return <section className="px-5 py-16 text-center"><h2 className="text-3xl font-light">Confiança para realizar seu próximo negócio</h2><p className="mt-3 text-slate-500">Atendimento profissional e personalizado do início ao fim.</p></section>;
  if(block.type==="development_feature"||block.type==="development_carousel") return <section className="bg-stone-50 px-5 py-16"><div className="mx-auto max-w-7xl text-center"><HouseLine size={38} className="mx-auto text-[var(--grey-olive)]"/><h2 className="mt-4 text-3xl font-light">Empreendimento em destaque</h2><p className="mt-3 text-slate-500">Solicite informações completas no formulário desta página.</p></div></section>;
  return null;
}

function LandingForm({pageId,blockId,data}:{pageId:string;blockId:string;data:Extract<LandingPageBlock,{type:"lead_form"}>["data"]}){const [values,setValues]=useState<Record<string,string>>({});const[status,setStatus]=useState<"idle"|"sending"|"success"|"error">("idle");const started=useRef(false);async function submit(event:React.FormEvent){event.preventDefault();setStatus("sending");const attribution=getBrowserAttributionContext();const token=await getAccessToken();const headers:Record<string,string>={"content-type":"application/json"};if(token)headers.authorization=`Bearer ${token}`;const response=await fetch(`/api/public/landing-pages/${pageId}/lead`,{method:"POST",headers,body:JSON.stringify({...values,...attribution,block_id:blockId,utm:{source:attribution.source,medium:attribution.medium,campaign:attribution.campaign,content:attribution.content,term:attribution.term},website:values.website})});setStatus(response.ok?"success":"error");}function start(){if(started.current)return;started.current=true;void track(pageId,"FORM_START",{block_id:blockId});}if(status==="success")return <section id="formulario" className="bg-stone-100 px-5 py-20"><div className="mx-auto max-w-xl rounded-2xl bg-white p-10 text-center shadow-xl"><CheckCircle size={48} className="mx-auto text-emerald-600"/><h2 className="mt-4 text-2xl font-medium">{data.successMessage}</h2></div></section>;return <section id="formulario" className="bg-stone-100 px-5 py-20"><form onSubmit={submit} onFocus={start} className="mx-auto max-w-2xl rounded-2xl bg-white p-6 shadow-xl md:p-10"><h2 className="text-3xl font-light">{data.title}</h2>{data.subtitle?<p className="mt-3 text-slate-500">{data.subtitle}</p>:null}<input tabIndex={-1} autoComplete="off" value={values.website??""} onChange={(e)=>setValues({...values,website:e.target.value})} className="hidden" aria-hidden="true"/>
  <div className="mt-7 grid gap-4 md:grid-cols-2">{(["nome","sobrenome","email","telefone","mensagem"] as LandingPageFormField[]).map((field)=><FormField key={field} field={field} value={values[field]??""} required={field==="nome"||field==="sobrenome"||field==="telefone"||(field==="email"&&!data.emailOptional)} onChange={(value)=>setValues({...values,[field]:value})}/>)}</div><label className="mt-5 flex items-start gap-2 text-xs leading-5 text-slate-500"><input type="checkbox" required className="mt-1"/>Concordo com o uso dos meus dados para atendimento desta solicitação, conforme a política de privacidade.</label>{status==="error"?<p className="mt-4 text-sm text-red-600">Não foi possível enviar. Revise os campos e tente novamente.</p>:null}<button disabled={status==="sending"} className="mt-6 w-full rounded-xl bg-slate-950 px-5 py-3.5 font-bold text-white disabled:opacity-50">{status==="sending"?"Enviando...":data.buttonLabel}</button></form></section>}
function FormField({field,value,required,onChange}:{field:LandingPageFormField;value:string;required:boolean;onChange:(value:string)=>void}){const labels:Record<LandingPageFormField,string>={nome:"Nome",sobrenome:"Sobrenome",telefone:"Telefone",email:"E-mail",mensagem:"Mensagem",objetivo:"Objetivo",tipo_uso:"Tipo de uso",tipo_imovel:"Tipo de imóvel",faixa_valor:"Faixa de valor",dormitorios:"Dormitórios",localizacao:"Localização"};if(field==="mensagem")return <label className="grid gap-1 md:col-span-2 text-sm">{labels[field]}<textarea value={value} required={required} onChange={(e)=>onChange(e.target.value)} className="min-h-28 rounded-xl border border-slate-200 px-3 py-2"/></label>;if(field==="objetivo")return <label className="grid gap-1 text-sm">{labels[field]}<select value={value} required={required} onChange={(e)=>onChange(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5"><option value="">Selecione</option><option value="COMPRAR">Comprar</option><option value="ALUGAR">Alugar</option><option value="VENDER">Vender</option></select></label>;return <label className="grid gap-1 text-sm">{labels[field]}<input type={field==="email"?"email":field==="telefone"?"tel":"text"} value={value} required={required} onChange={(e)=>onChange(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5"/></label>}
async function track(pageId:string,event_type:"VIEW"|"FORM_START"|"CTA_CLICK",metadata:Record<string,unknown>={}){try{await trackPublicEvent("LANDING_PAGE",pageId,event_type,metadata);}catch{/* métricas não podem interromper a página */}}
function youtubeEmbed(url:string){try{const parsed=new URL(url);const id=parsed.hostname.includes("youtu.be")?parsed.pathname.slice(1):parsed.searchParams.get("v");return id?`https://www.youtube-nocookie.com/embed/${id}`:url;}catch{return url;}}
