import { NextResponse } from "next/server";
import { statusFromErrorCode } from "@/lib/api/result";
import { captureLeadByKeys } from "@/lib/db/leads";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { recordPublicEvent, snapshotLeadAttribution } from "@/lib/marketing/attribution";

type Context={params:Promise<{id:string}>};
function text(value:unknown,max=1000){return typeof value==="string"?value.trim().slice(0,max):"";}
function phoneE164(value:string){const digits=value.replace(/\D/g,"");if((digits.length===12||digits.length===13)&&digits.startsWith("55"))return`+${digits}`;if(digits.length===10||digits.length===11)return`+55${digits}`;return null;}
export async function POST(request:Request,{params}:Context){let body:unknown;try{body=await request.json();}catch{return NextResponse.json({ok:false,error:{message:"Dados inválidos"}},{status:400});}if(!body||typeof body!=="object")return NextResponse.json({ok:false},{status:400});const data=body as Record<string,unknown>;if(text(data.website))return NextResponse.json({ok:true,data:{accepted:true}});const id=(await params).id;const admin=createSupabaseAdminClient();const page=await admin.from("landing_pages").select("id,owner_id,status,tipo,slug,titulo,empreendimento_id,imovel_id,conteudo_blocos").eq("id",id).eq("status","PUBLICADO").maybeSingle();if(page.error||!page.data)return NextResponse.json({ok:false,error:{message:"Página não encontrada"}},{status:404});const firstName=text(data.nome,100);const lastName=text(data.sobrenome,100);const nome=[firstName,lastName].join(" ");const email=text(data.email,200).toLowerCase()||null;const telefone=text(data.telefone,30)||null;const e164=phoneE164(telefone??"");const content=page.data.conteudo_blocos as {blocks?:Array<{id?:string;type?:string;data?:{emailOptional?:boolean}}>}|null;const requestedBlockId=text(data.block_id,80);const formBlock=content?.blocks?.find((block)=>block.type==="lead_form"&&(!requestedBlockId||block.id===requestedBlockId));const emailOptional=formBlock?.data?.emailOptional===true;if(!firstName||!lastName||!e164||(!emailOptional&&!email)||email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return NextResponse.json({ok:false,error:{message:"Informe nome, sobrenome, telefone e e-mail válidos"}},{status:400});const objetivo=["COMPRAR","ALUGAR","VENDER"].includes(text(data.objetivo,20))?text(data.objetivo,20):null;const pageUrl=text(data.page_url,1000)||null;const lead=await captureLeadByKeys({owner_id:page.data.owner_id,nome,email,telefone,telefone_e164:e164,origem:"CORRETOR_ONE",mensagem:text(data.mensagem),imovel_id:page.data.imovel_id,utm:data.utm&&typeof data.utm==="object"?data.utm as Record<string,unknown>:null,form_key:"landing_page",page_url:pageUrl,referrer:text(data.referrer,1000)||null,form_payload:{form_key:"landing_page",briefing:{objetivolead:objetivo?[objetivo]:null,tipouso:text(data.tipo_uso,30)||null,tipoimovel:text(data.tipo_imovel,80)?[text(data.tipo_imovel,80)]:null,localizacao_texto:text(data.localizacao,180)||null},context:{landing_page_id:id,landing_page_slug:page.data.slug,landing_page_type:page.data.tipo,block_id:requestedBlockId,empreendimento_id:page.data.empreendimento_id}}});if(!lead.ok)return NextResponse.json(lead,{status:statusFromErrorCode(lead.error.code)});
  if(objetivo){const tiponegociacao: Array<"ALUGUEL"|"VENDA">=objetivo==="ALUGAR"?["ALUGUEL"]:["VENDA"];await admin.from("lead_briefings").upsert({owner_id:page.data.owner_id,lead_id:lead.data.lead_id,objetivolead:[objetivo as "COMPRAR"|"ALUGAR"|"VENDER"],tiponegociacao,localizacao_texto:text(data.localizacao,180)||null,texto_livre:text(data.mensagem)||null},{onConflict:"lead_id"});}
  if(page.data.empreendimento_id)await admin.from("lead_empreendimentos").upsert({owner_id:page.data.owner_id,lead_id:lead.data.lead_id,empreendimento_id:page.data.empreendimento_id},{onConflict:"lead_id,empreendimento_id"});
  const visitorId=text(data.visitor_id,40);const sessionId=text(data.session_id,40);const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;const authorization=request.headers.get("authorization");let isOwner=false;if(authorization?.startsWith("Bearer ")){const authenticated=await admin.auth.getUser(authorization.slice(7));isOwner=authenticated.data.user?.id===page.data.owner_id;}
  if(!isOwner&&uuid.test(visitorId)&&uuid.test(sessionId)){try{const clickIds=data.click_ids&&typeof data.click_ids==="object"?Object.fromEntries(Object.entries(data.click_ids as Record<string,unknown>).filter((entry):entry is [string,string]=>typeof entry[1]==="string")):{};const conversion=await recordPublicEvent(admin,{ownerId:page.data.owner_id,resourceType:"LANDING_PAGE",resourceId:id,eventType:"FORM_SUBMIT",context:{visitorId,sessionId,pageUrl,referrer:text(data.referrer,1000)||null,source:text(data.source,200)||null,medium:text(data.medium,200)||null,campaign:text(data.campaign,300)||null,content:text(data.content,300)||null,term:text(data.term,300)||null,clickIds},metadata:{lead_id:lead.data.lead_id,action:lead.data.action,block_id:requestedBlockId}});await snapshotLeadAttribution(admin,{ownerId:page.data.owner_id,leadId:lead.data.lead_id,conversionEventId:conversion.eventId,visitorId});}catch{/* atribuição não pode interromper a captação */}}
  await admin.from("timeline_eventos").insert({owner_id:page.data.owner_id,lead_id:lead.data.lead_id,negocio_id:null,tipo:"SISTEMA",titulo:`Formulário enviado: ${page.data.titulo}`,detalhes:{landing_page_id:id,page_url:pageUrl}});
  return NextResponse.json({ok:true,data:{accepted:true,action:lead.data.action}});
}
