"use client";

import Image from "next/image";
import { ArrowClockwise, Bed, BookmarkSimple, Car, ChatCircle, Check, DownloadSimple, Heart, House, ImageSquare, PaperPlaneTilt, Ruler, Sparkle, UserCircle } from "@phosphor-icons/react";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/app/_components/app-shell";
import { apiFetchWithAuth } from "@/lib/client/auth-api";
import { CREATIVE_DIMENSIONS, type CreativeFormat } from "@/lib/creatives/static-template";

type Template={id:string;nome:string;renderer_key:string;formatos:CreativeFormat[];mode:"FIXED"|"HYBRID"};
type Property={id:string;titulo:string;display_title:string;short_title:string;codigo:string|null;finalidade:string;tipo:string;bairro_comercial:string|null;bairro:string;cidade:string;estado:string;preco_venda:number|null;preco_locacao:number|null;area_util:number|null;dormitorios:number|null;suites:number|null;vagas:number|null;images:string[]};
type Profile={nickname:string;primeiro_nome:string;sobrenome:string;avatar_url:string|null;logo_nickname_url:string|null;logo_nickname_white_url:string|null;creci_uf:string;creci_numero:string};
type Post={id:string;formato:CreativeFormat;status:"GERANDO"|"PRONTO"|"ERRO";resultado_url:string|null;payload:{property?:{title?:string}}};
type Bootstrap={templates:Template[];properties:Property[];profile:Profile;posts:Post[]};
type PreviewMode="INSTAGRAM_FEED"|"STORY_STATUS";
type TitleMode="FULL"|"SHORT";

const money=(value:number|null)=>value?new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(value):"Consulte o valor";

export default function CreativesPage(){
  const[data,setData]=useState<Bootstrap|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
  const[templateId,setTemplateId]=useState("");const[propertyId,setPropertyId]=useState("");const[imageUrl,setImageUrl]=useState("");const[format,setFormat]=useState<CreativeFormat>("PORTRAIT");const[titleMode,setTitleMode]=useState<TitleMode>("FULL");
  const[headline,setHeadline]=useState("");const[supportingText,setSupportingText]=useState("");const[cta,setCta]=useState("Conheça todos os detalhes");const[generating,setGenerating]=useState(false);
  function apply(result:Bootstrap){setData(result);setTemplateId((current)=>current||result.templates[0]?.id||"");}
  function refresh(){apiFetchWithAuth<Bootstrap>("/api/criativos").then((result)=>result.ok?apply(result.data):setError(result.error));}
  useEffect(()=>{let active=true;apiFetchWithAuth<Bootstrap>("/api/criativos").then((result)=>{if(!active)return;if(result.ok)apply(result.data);else setError(result.error);setLoading(false);});return()=>{active=false};},[]);
  const property=useMemo(()=>data?.properties.find((item)=>item.id===propertyId)??null,[data,propertyId]);
  const template=data?.templates.find((item)=>item.id===templateId)??null;
  const previewMode:PreviewMode=format==="VERTICAL"?"STORY_STATUS":"INSTAGRAM_FEED";
  function chooseProperty(id:string){setPropertyId(id);const selected=data?.properties.find((item)=>item.id===id);setImageUrl(selected?.images[0]??"");setHeadline("");setSupportingText("");}
  async function generate(){if(!template||!property||!imageUrl)return;setGenerating(true);setError(null);const result=await apiFetchWithAuth<{url:string}>("/api/criativos",{method:"POST",body:JSON.stringify({template_id:template.id,property_id:property.id,image_url:imageUrl,format,title_mode:titleMode,headline,supporting_text:supportingText,cta})});setGenerating(false);if(!result.ok){setError(result.error);return}refresh();}

  return <AppShell title="Central de Criativos" subtitle="Crie materiais profissionais com a sua identidade." mainClassName="min-w-0"><div className="space-y-5">
    {error?<p className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>:null}{loading&&!data?<Loading/>:null}
    {data?<><Objective/><div className="grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(390px,.78fr)]"><div className="space-y-5">
      <Panel number="1" title="Escolha o imóvel"><select value={propertyId} onChange={(event)=>chooseProperty(event.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3"><option value="">Selecione um imóvel publicado</option>{data.properties.map((item)=><option key={item.id} value={item.id}>{item.codigo?`${item.codigo} · `:""}{item.titulo}</option>)}</select>{property?<div className="mt-4 grid grid-cols-4 gap-3 sm:grid-cols-6">{property.images.map((url,index)=><button key={url} type="button" onClick={()=>setImageUrl(url)} className={`relative aspect-square overflow-hidden rounded-xl border-2 ${imageUrl===url?"border-slate-950":"border-transparent"}`}><Image src={url} alt={`Imagem ${index+1}`} fill sizes="130px" className="object-cover" unoptimized/>{imageUrl===url?<span className="absolute right-1.5 top-1.5 rounded-full bg-slate-950 p-1 text-white"><Check size={12}/></span>:null}</button>)}</div>:null}</Panel>
      <Panel number="2" title="Escolha o template"><div className="grid gap-3 sm:grid-cols-2">{data.templates.map((item)=><button key={item.id} type="button" onClick={()=>setTemplateId(item.id)} className={`overflow-hidden rounded-xl border-2 text-left ${templateId===item.id?"border-slate-950":"border-slate-200"}`}><div className="relative aspect-[4/3] bg-stone-100"><div className="absolute inset-x-0 top-0 h-9 bg-white"/><div className="absolute inset-x-0 top-9 h-[58%] bg-gradient-to-br from-slate-300 to-slate-500"/><div className="absolute inset-x-4 bottom-4 space-y-2"><span className="block h-2 w-4/5 rounded bg-slate-800"/><span className="block h-1.5 w-3/5 rounded bg-slate-400"/></div>{templateId===item.id?<span className="absolute right-3 top-3 rounded-full bg-slate-950 p-1.5 text-white"><Check size={14}/></span>:null}</div><div className="p-3"><p className="font-semibold">{item.nome}</p><p className="mt-1 text-xs text-slate-500">{item.mode==="HYBRID"?"Personalizável":"Automático"}</p></div></button>)}<div className="flex min-h-40 items-center justify-center rounded-xl border border-dashed border-slate-200 text-center text-sm text-slate-400">Novos templates<br/>em breve</div></div></Panel>
      <Panel number="3" title="Formato e conteúdo"><div className="grid gap-3 sm:grid-cols-3">{(["SQUARE","PORTRAIT","VERTICAL"] as CreativeFormat[]).map((item)=><button key={item} type="button" onClick={()=>setFormat(item)} className={`rounded-xl border p-3 text-xs font-semibold ${format===item?"border-slate-950 bg-slate-950 text-white":"border-slate-200"}`}>{CREATIVE_DIMENSIONS[item].label}</button>)}</div><div className="mt-5 grid gap-4"><label className="grid gap-1.5 text-sm font-semibold">Título técnico<select value={titleMode} onChange={(event)=>setTitleMode(event.target.value as TitleMode)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 font-normal"><option value="FULL">Título completo do single</option><option value="SHORT">Tipo do imóvel e finalidade</option></select></label><Field label="Headline publicitária (opcional)" value={headline} max={60} onChange={setHeadline}/><Field label="Texto de apoio (opcional)" value={supportingText} max={60} onChange={setSupportingText}/>{format!=="VERTICAL"&&titleMode==="FULL"?<p className="text-xs text-slate-500">No feed, headline e texto de apoio não aparecem quando o título completo está selecionado.</p>:null}<label className="grid gap-1.5 text-sm font-semibold">Chamada para ação<select value={cta} onChange={(event)=>setCta(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 font-normal"><option>Conheça todos os detalhes</option><option>Agende uma visita</option><option>Fale comigo</option><option>Veja este imóvel</option><option>Solicite mais informações</option></select></label></div></Panel>
    </div><aside className="xl:sticky xl:top-5 xl:self-start"><Panel number="4" title="Preview"><PreviewFrame mode={previewMode}><CreativeArtwork property={property} profile={data.profile} imageUrl={imageUrl} format={format} titleMode={titleMode} headline={headline} supportingText={supportingText} cta={cta}/></PreviewFrame><button type="button" disabled={!template||!property||!imageUrl||!cta||generating} onClick={()=>void generate()} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--primary-scarlet)] px-5 py-3.5 font-bold text-white disabled:opacity-40">{generating?<><ArrowClockwise className="animate-spin"/>Gerando...</>:<><Sparkle/>Gerar criativo</>}</button><p className="mt-3 text-center text-xs text-slate-400">A moldura e os controles sociais não entram no PNG.</p></Panel></aside></div><History posts={data.posts}/></>:null}
  </div></AppShell>;
}

function Objective(){return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-950 text-white"><House size={21}/></span><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--grey-olive)]">Objetivo selecionado</p><h2 className="text-xl font-semibold">Promover um imóvel</h2></div></div></section>}
function Panel({number,title,children}:{number:string;title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-stone-100 text-sm font-bold text-[var(--grey-olive)]">{number}</span><h2 className="text-lg font-semibold">{title}</h2></div>{children}</section>}
function Field({label,value,max,onChange,multiline=false}:{label:string;value:string;max:number;onChange:(value:string)=>void;multiline?:boolean}){const classes="rounded-xl border border-slate-200 px-3 py-2.5 font-normal";return <label className="grid gap-1.5 text-sm font-semibold"><span className="flex justify-between"><span>{label}</span><span className="text-xs font-normal text-slate-400">{value.length}/{max}</span></span>{multiline?<textarea value={value} maxLength={max} onChange={(event)=>onChange(event.target.value)} className={`${classes} min-h-20`}/>:<input value={value} maxLength={max} onChange={(event)=>onChange(event.target.value)} className={classes}/>}</label>}
function Loading(){return <div className="flex min-h-64 items-center justify-center text-sm text-slate-500"><ArrowClockwise className="mr-2 animate-spin"/>Carregando...</div>}

function CreativeArtwork({property,profile,imageUrl,format,titleMode,headline,supportingText,cta}:{property:Property|null;profile:Profile;imageUrl:string;format:CreativeFormat;titleMode:TitleMode;headline:string;supportingText:string;cta:string}){const title=property?(titleMode==="SHORT"?property.short_title:property.display_title):"Título do imóvel";if(format==="VERTICAL")return <VerticalArtwork property={property} profile={profile} imageUrl={imageUrl} title={title} headline={headline} supportingText={supportingText} cta={cta}/>;return <StandardArtwork property={property} profile={profile} imageUrl={imageUrl} format={format} titleMode={titleMode} title={title} headline={headline} supportingText={supportingText} cta={cta}/>}
function StandardArtwork({property,profile,imageUrl,format,titleMode,title,headline,supportingText,cta}:{property:Property|null;profile:Profile;imageUrl:string;format:Exclude<CreativeFormat,"VERTICAL">;titleMode:TitleMode;title:string;headline:string;supportingText:string;cta:string}){const showCopy=titleMode==="SHORT";const ratio=format==="SQUARE"?"aspect-square":"aspect-[4/5]";return <div className={`relative w-full overflow-hidden bg-[#f7f5ef] text-slate-950 ${ratio}`}><div className="relative h-[60%]">{imageUrl?<Image src={imageUrl} alt="" fill sizes="430px" className="object-cover" unoptimized/>:<div className="flex h-full items-center justify-center bg-slate-200"><ImageSquare size={38}/></div>}<div className="absolute inset-0 bg-gradient-to-b from-black/80 via-transparent via-45% to-slate-950/80"/><header className="absolute inset-x-[5%] top-[7%] flex items-center justify-between text-white"><BrokerIdentity profile={profile} inverse/>{profile.logo_nickname_white_url?<Image src={profile.logo_nickname_white_url} alt={`corretor.one/${profile.nickname}`} width={105} height={34} className="h-7 w-auto object-contain" unoptimized/>:<p className="text-[9px] font-bold text-white">corretor.one/{profile.nickname}</p>}</header><div className="absolute inset-x-[5%] bottom-[7%] flex items-center justify-between gap-3 text-[8px] font-bold text-white"><p>{location(property)}</p><p className="shrink-0">{property?.codigo||""}</p></div></div><div className="absolute inset-x-0 bottom-0 top-[60%] flex flex-col px-[5%] py-[4%]"><h3 className={`${titleMode==="FULL"?(format==="SQUARE"?"line-clamp-2 text-[clamp(10px,2.1vw,15px)]":"line-clamp-3 text-[clamp(11px,2.5vw,17px)]"):(format==="SQUARE"?"line-clamp-2 text-[clamp(11px,2.45vw,17px)]":"line-clamp-3 text-[clamp(12px,3vw,21px)]")} font-normal leading-[1.08] tracking-tight`}>{title}</h3>{showCopy&&headline?<p className="mt-1.5 truncate whitespace-nowrap text-[9px] font-semibold text-slate-600">{headline}</p>:null}{showCopy&&supportingText?<p className="mt-1 truncate whitespace-nowrap text-[7px] text-slate-500">{supportingText}</p>:null}<Stats property={property}/><div className="mt-auto flex items-end justify-between border-t border-stone-300 pt-2"><p className="text-[12px] font-bold">{price(property)}</p><p className="text-right text-[7px] font-bold text-[var(--grey-olive)]">{cta}</p></div></div></div>}
function VerticalArtwork({property,profile,imageUrl,title,headline,supportingText,cta}:{property:Property|null;profile:Profile;imageUrl:string;title:string;headline:string;supportingText:string;cta:string}){return <div className="relative aspect-[9/16] w-full overflow-hidden bg-[#f7f5ef] text-slate-950"><div className="relative h-[60%]">{imageUrl?<Image src={imageUrl} alt="" fill sizes="430px" className="object-cover" unoptimized/>:<div className="flex h-full items-center justify-center bg-slate-300"><ImageSquare size={38}/></div>}<div className="absolute inset-0 bg-gradient-to-b from-black/85 via-transparent via-45% to-slate-950/80"/><header className="absolute inset-x-[6%] top-[11%] flex items-center justify-between text-white"><BrokerIdentity profile={profile} inverse/>{profile.logo_nickname_white_url?<Image src={profile.logo_nickname_white_url} alt={`corretor.one/${profile.nickname}`} width={105} height={34} className="h-7 w-auto object-contain" unoptimized/>:<p className="text-[9px] font-bold text-white">corretor.one/{profile.nickname}</p>}</header><div className="absolute inset-x-[6%] bottom-[6%] flex items-center justify-between gap-3 text-[8px] font-bold text-white"><p>{location(property)}</p><p className="shrink-0">{property?.codigo||""}</p></div></div><div className="absolute inset-x-0 bottom-0 top-[60%] flex flex-col px-[6%] pb-[16%] pt-[4%]"><h3 className="line-clamp-3 text-[16px] font-semibold leading-[1.06] tracking-tight">{title}</h3>{headline?<p className="mt-1 line-clamp-1 text-[8px] font-semibold text-slate-600">{headline}</p>:null}{supportingText?<p className="mt-0.5 line-clamp-1 text-[6px] text-slate-500">{supportingText}</p>:null}<Stats property={property} vertical/><div className="mt-2 grid grid-cols-[1fr_auto] items-center gap-2"><p className="text-[12px] font-bold">{price(property)}</p><p className="rounded-full bg-slate-950 px-3 py-2 text-center text-[7px] font-bold text-white">{cta}</p></div></div></div>}
function BrokerIdentity({profile,inverse=false}:{profile:Profile;inverse?:boolean}){return <div className="flex min-w-0 items-center gap-2">{profile.avatar_url?<Image src={profile.avatar_url} alt="" width={34} height={34} className={`h-8 w-8 rounded-full object-cover ${inverse?"border border-white/80":""}`} unoptimized/>:<UserCircle size={32}/>}<div className="min-w-0"><p className="truncate text-[8px] font-bold">{profile.primeiro_nome} {profile.sobrenome}</p><p className={`text-[6px] ${inverse?"text-white/80":"text-slate-500"}`}>{profile.creci_uf} {profile.creci_numero}-F</p></div></div>}
function Stats({property,vertical=false}:{property:Property|null;vertical?:boolean}){const items=[[property?.area_util,"m² úteis",Ruler],[property?.dormitorios,"Dorm.",Bed],[property?.suites,"Suítes",House],[property?.vagas,"Vagas",Car]] as const;return <div className={`${vertical?"mt-2":"mt-3"} grid w-full grid-cols-4 border-y border-stone-300 py-2`}>{items.map(([value,label,Icon])=><span key={label} className="flex items-center justify-center gap-1 border-r border-stone-300 text-[6px] text-slate-600 last:border-r-0"><Icon size={12} className="shrink-0 text-[var(--grey-olive)]"/><span><b className="block leading-none">{Number(value)>0?value:"—"}</b>{label}</span></span>)}</div>}
function location(property:Property|null){return property?[property.bairro_comercial||property.bairro,`${property.cidade}/${property.estado}`].filter(Boolean).join(" · "):"Localização"}
function price(property:Property|null){return property?money(property.finalidade==="ALUGAR"?property.preco_locacao:property.preco_venda):"Consulte o valor"}

function PreviewFrame({mode,children}:{mode:PreviewMode;children:React.ReactNode}){const story=mode==="STORY_STATUS";return <div className="mx-auto max-w-[330px] rounded-[42px] border-[9px] border-slate-950 bg-slate-950 p-1 shadow-2xl"><div className={`relative overflow-hidden rounded-[30px] bg-white ${story?"aspect-[9/19.5]":"min-h-[600px]"}`}><div className="flex h-7 items-center justify-between px-5 text-[8px] font-bold"><span>9:41</span><span>●●●</span></div>{!story?<><div className="flex items-center gap-2 border-y border-slate-100 px-3 py-2"><span className="h-6 w-6 rounded-full bg-slate-300"/><span className="text-[8px] font-bold">seu perfil</span></div>{children}<div className="flex items-center justify-between p-3"><span className="flex gap-3"><Heart size={18}/><ChatCircle size={18}/><PaperPlaneTilt size={18}/></span><BookmarkSimple size={18}/></div><p className="px-3 pb-4 text-[8px]"><b>seu perfil</b> Conheça este imóvel.</p></>:<div className="absolute inset-x-0 bottom-0 top-7 bg-slate-800"><div className="absolute inset-0 [&>*]:h-full [&>*]:w-full">{children}</div><div className="pointer-events-none absolute inset-x-2 top-2 z-20 flex gap-1">{[1,2,3].map((item)=><span key={item} className="h-0.5 flex-1 bg-white/80"/>)}</div><div className="pointer-events-none absolute inset-x-4 bottom-6 z-20 h-9 rounded-full border border-white/80"/><span className="absolute bottom-1 left-0 right-0 z-20 text-center text-[7px] text-white">Enviar mensagem</span></div>}</div></div>}
function History({posts}:{posts:Post[]}){return <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="border-b border-slate-100 p-5"><h2 className="text-lg font-semibold">Criativos gerados</h2></header>{posts.length?<div className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4">{posts.map((post)=><article key={post.id} className="overflow-hidden rounded-xl border border-slate-200"><div className="relative aspect-square bg-slate-100">{post.resultado_url?<Image src={post.resultado_url} alt="Criativo" fill sizes="300px" className="object-cover" unoptimized/>:null}</div><div className="p-3"><p className="truncate text-sm font-semibold">{post.payload?.property?.title??"Imóvel"}</p>{post.resultado_url?<a href={post.resultado_url} target="_blank" rel="noreferrer" className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-lg border px-3 py-2 text-sm"><DownloadSimple/>Baixar PNG</a>:null}</div></article>)}</div>:<p className="p-10 text-center text-sm text-slate-400">Nenhum criativo gerado.</p>}</section>}
