export type CreativeFormat = "SQUARE" | "PORTRAIT" | "VERTICAL";

export type PropertyCreativePayload = {
  property: { id: string; title: string; location: string; price: string; code: string; imageUrl: string; stats: Array<{ kind: "BED" | "SUITE" | "CAR" | "AREA"; value: string; label: string }> };
  broker: { name: string; nickname: string; creci: string; avatarUrl: string | null; logoUrl: string | null; logoWhiteUrl: string | null };
  copy: { headline: string; supportingText: string; cta: string; titleMode: "FULL" | "SHORT" };
  format: CreativeFormat;
};

export const CREATIVE_DIMENSIONS: Record<CreativeFormat, { width: number; height: number; label: string }> = {
  SQUARE: { width: 1080, height: 1080, label: "Square · 1080 × 1080" },
  PORTRAIT: { width: 1080, height: 1350, label: "Feed 4:5 · 1080 × 1350" },
  VERTICAL: { width: 1080, height: 1920, label: "Stories/Status · 1080 × 1920" },
};

function escape(value: string) { return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[char] ?? char); }
function safeUrl(value: string | null) { try { const url = new URL(value ?? ""); return ["http:", "https:"].includes(url.protocol) ? escape(url.href) : ""; } catch { return ""; } }
function statIcon(kind: PropertyCreativePayload["property"]["stats"][number]["kind"]) {
  if (kind === "BED") return `<svg viewBox="0 0 24 24"><path d="M3 18v-7m18 7v-5a2 2 0 0 0-2-2H9a2 2 0 0 0-2 2v5m-4-2h18M7 11V8a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3"/></svg>`;
  if (kind === "SUITE") return `<svg viewBox="0 0 24 24"><path d="M4 20V5a1 1 0 0 1 1-1h11a1 1 0 0 1 1 1v15M4 20h16M14 12h.01"/></svg>`;
  if (kind === "CAR") return `<svg viewBox="0 0 24 24"><path d="m5 11 2-5h10l2 5M4 11h16v7H4zM7 15h.01M17 15h.01M6 18v2m12-2v2"/></svg>`;
  return `<svg viewBox="0 0 24 24"><path d="M4 20 20 4M8 4H4v4M16 20h4v-4M14 4h6v6M10 20H4v-6"/></svg>`;
}

type CreativeFonts = { light: string; book: string; bold: string };
function fontFaces(fonts?: CreativeFonts) { return fonts ? `@font-face{font-family:"dunbar-tall";src:url("${fonts.light}") format("woff2");font-weight:300}@font-face{font-family:"dunbar-tall";src:url("${fonts.book}") format("woff2");font-weight:400}@font-face{font-family:"dunbar-tall";src:url("${fonts.bold}") format("woff2");font-weight:700}` : ""; }

export function buildPropertyEssentialHtml(payload: PropertyCreativePayload, fonts?: CreativeFonts) {
  const { width, height } = CREATIVE_DIMENSIONS[payload.format];
  const vertical = payload.format === "VERTICAL";
  const portrait = payload.format === "PORTRAIT";
  const headerHeight = vertical ? 154 : 116;
  const imageHeight = vertical ? 990 : portrait ? 670 : 545;
  const avatar = safeUrl(payload.broker.avatarUrl);
  const logo = safeUrl(payload.broker.logoUrl);
  const whiteLogo = safeUrl(payload.broker.logoWhiteUrl);
  if (vertical) return `<!doctype html><html><head><meta charset="utf-8"><style>${fontFaces(fonts)}html,body{font-family:"dunbar-tall",Arial,sans-serif!important;font-weight:300}.title{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:3;overflow:hidden;font-size:44px!important;font-weight:400!important}.headline,.support{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.broker,.brandText,.location,.factValue,.price,.cta{font-weight:700!important}
  *{box-sizing:border-box}html,body{margin:0;width:1080px;height:1920px;overflow:hidden;font-family:Arial,Helvetica,sans-serif;background:#f7f5ef;color:#101827}.canvas{position:relative;width:1080px;height:1920px;overflow:hidden;background:#f7f5ef}.hero{position:relative;height:1152px}.photo{width:100%;height:100%;object-fit:cover}.topShade{position:absolute;inset:0;background:linear-gradient(180deg,rgba(0,0,0,.82) 0,rgba(0,0,0,.4) 15%,transparent 42%,transparent 68%,rgba(8,15,28,.84) 100%)}.header{position:absolute;z-index:2;left:64px;right:64px;top:130px;display:flex;align-items:center;justify-content:space-between;color:#fff}.identity{display:flex;align-items:center;gap:18px}.avatar{width:82px;height:82px;border:2px solid rgba(255,255,255,.86);border-radius:50%;object-fit:cover}.avatarFallback{display:flex;align-items:center;justify-content:center;background:#111827;color:#fff;font-size:28px}.broker{font-size:26px;font-weight:800;text-shadow:0 1px 12px rgba(0,0,0,.35)}.creci{margin-top:6px;font-size:18px;color:rgba(255,255,255,.82)}.brandLogo{max-width:300px;max-height:72px;object-fit:contain;filter:drop-shadow(0 1px 10px rgba(0,0,0,.28))}.brandText{font-size:27px;font-weight:800;letter-spacing:-.04em;color:#fff}.location{position:absolute;left:64px;right:220px;bottom:54px;color:#fff;font-size:27px;font-weight:700}.code{position:absolute;right:64px;bottom:58px;color:rgba(255,255,255,.82);font-size:18px}.body{height:768px;padding:42px 64px 150px;display:flex;flex-direction:column}.title{margin:0;font-size:48px;line-height:1.06;letter-spacing:-.035em;font-weight:650}.headline{margin:15px 0 0;color:#525b67;font-size:25px;line-height:1.25}.support{margin:7px 0 0;color:#737b86;font-size:19px;line-height:1.25}.facts{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));width:100%;margin-top:28px;padding:23px 0;border-top:1px solid #d9d6cb;border-bottom:1px solid #d9d6cb}.fact{display:flex;align-items:center;justify-content:center;gap:11px;min-width:0;border-right:1px solid #d9d6cb}.fact:last-child{border-right:0}.fact svg{width:31px;height:31px;flex:0 0 auto;fill:none;stroke:#918b76;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.factValue{font-size:24px;font-weight:800}.factLabel{font-size:15px;color:#737b86;white-space:nowrap}.conversion{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:30px;margin-top:28px}.price{font-size:42px;font-weight:800}.cta{min-width:305px;padding:20px 28px;border-radius:999px;background:#101827;color:#fff;text-align:center;font-size:21px;font-weight:800}
  </style></head><body><div class="canvas"><div class="hero"><img class="photo" src="${safeUrl(payload.property.imageUrl)}"><div class="topShade"></div><header class="header"><div class="identity">${avatar ? `<img class="avatar" src="${avatar}">` : `<div class="avatar avatarFallback">${escape(payload.broker.name.slice(0,1))}</div>`}<div><div class="broker">${escape(payload.broker.name)}</div><div class="creci">${escape(payload.broker.creci)}</div></div></div>${whiteLogo ? `<img class="brandLogo" src="${whiteLogo}">` : `<div class="brandText">corretor.one/${escape(payload.broker.nickname)}</div>`}</header><div class="location">${escape(payload.property.location)}</div><div class="code">${escape(payload.property.code)}</div></div><div class="body"><h1 class="title">${escape(payload.property.title)}</h1>${payload.copy.headline ? `<p class="headline">${escape(payload.copy.headline)}</p>` : ""}${payload.copy.supportingText ? `<p class="support">${escape(payload.copy.supportingText)}</p>` : ""}<div class="facts">${payload.property.stats.map((item) => `<div class="fact">${statIcon(item.kind)}<div><div class="factValue">${escape(item.value)}</div><div class="factLabel">${escape(item.label)}</div></div></div>`).join("")}</div><div class="conversion"><div class="price">${escape(payload.property.price)}</div><div class="cta">${escape(payload.copy.cta)}</div></div></div></div></body></html>`;
  return `<!doctype html><html><head><meta charset="utf-8"><style>${fontFaces(fonts)}html,body{font-family:"dunbar-tall",Arial,sans-serif!important;font-weight:300}.title{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:${portrait ? 3 : 2};overflow:hidden;font-size:${payload.copy.titleMode === "FULL" ? (portrait ? 32 : 25) : (portrait ? 39 : 30)}px!important;font-weight:400!important}.headline,.support{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.broker,.brandText,.tag,.location,.factValue,.price,.cta{font-weight:700!important}.header{position:absolute!important;z-index:2;left:0;right:0;top:0;background:transparent!important;color:#fff}.creci{color:rgba(255,255,255,.82)!important}.photoWrap{height:${headerHeight + imageHeight}px!important}.shade{background:linear-gradient(180deg,rgba(0,0,0,.78) 0,transparent 38%,transparent 48%,rgba(8,15,28,.86) 100%)!important}.facts{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr));width:100%;gap:0!important;padding:18px 0;border-top:1px solid #d9d6cb;border-bottom:1px solid #d9d6cb}.fact{justify-content:center;border-right:1px solid #d9d6cb}.fact:last-child{border-right:0}
  *{box-sizing:border-box}html,body{margin:0;width:${width}px;height:${height}px;overflow:hidden;font-family:Arial,Helvetica,sans-serif;background:#f7f5ef;color:#101827}.canvas{position:relative;width:${width}px;height:${height}px;overflow:hidden;background:#f7f5ef}.header{height:${headerHeight}px;padding:24px 56px;display:flex;align-items:center;justify-content:space-between;background:#fff}.identity{display:flex;align-items:center;gap:16px}.avatar{width:${vertical ? 82 : 64}px;height:${vertical ? 82 : 64}px;border-radius:50%;object-fit:cover}.avatarFallback{display:flex;align-items:center;justify-content:center;background:#111827;color:#fff;font-size:24px}.broker{font-size:${vertical ? 25 : 20}px;font-weight:800}.creci{margin-top:5px;color:#737b86;font-size:${vertical ? 18 : 15}px}.brandLogo{max-width:${vertical ? 290 : 235}px;max-height:${vertical ? 68 : 52}px;object-fit:contain}.brandText{font-size:${vertical ? 27 : 22}px;font-weight:800;letter-spacing:-.04em}.photoWrap{position:relative;height:${imageHeight}px}.photo{width:100%;height:100%;object-fit:cover}.shade{position:absolute;inset:0;background:linear-gradient(180deg,transparent 45%,rgba(8,15,28,.86))}.tag{position:absolute;top:38px;left:56px;padding:13px 20px;border-radius:999px;background:#fff;font-size:18px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.location{position:absolute;left:56px;right:180px;bottom:38px;color:#fff;font-size:${vertical ? 27 : 23}px;font-weight:700}.code{position:absolute;right:56px;bottom:41px;color:#fff;font-size:17px}.body{height:${height-headerHeight-imageHeight}px;padding:${vertical ? "58px 64px 60px" : "38px 56px 42px"};display:flex;flex-direction:column}.title{margin:0;font-size:${vertical ? 54 : portrait ? 39 : 34}px;line-height:1.08;letter-spacing:-.035em;font-weight:600}.headline{margin:${vertical ? 24 : 14}px 0 0;color:#5b6472;font-size:${vertical ? 28 : 20}px;line-height:1.3}.support{margin:8px 0 0;color:#737b86;font-size:${vertical ? 21 : 16}px;line-height:1.3}.facts{display:flex;gap:${vertical ? 28 : 20}px;margin-top:${vertical ? 38 : 23}px}.fact{display:flex;align-items:center;gap:10px;color:#3f4753}.fact svg{width:${vertical ? 34 : 27}px;height:${vertical ? 34 : 27}px;fill:none;stroke:#918b76;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.factValue{font-size:${vertical ? 25 : 20}px;font-weight:800}.factLabel{font-size:${vertical ? 17 : 13}px;color:#737b86}.bottom{margin-top:auto;display:flex;align-items:end;justify-content:space-between;border-top:1px solid #d9d6cb;padding-top:${vertical ? 28 : 18}px}.price{font-size:${vertical ? 43 : 32}px;font-weight:800}.cta{text-align:right;color:#918b76;font-size:${vertical ? 23 : 17}px;font-weight:800}
  </style></head><body><div class="canvas"><header class="header"><div class="identity">${avatar ? `<img class="avatar" src="${avatar}">` : `<div class="avatar avatarFallback">${escape(payload.broker.name.slice(0,1))}</div>`}<div><div class="broker">${escape(payload.broker.name)}</div><div class="creci">${escape(payload.broker.creci)}</div></div></div>${whiteLogo ? `<img class="brandLogo" src="${whiteLogo}">` : `<div class="brandText">corretor.one/${escape(payload.broker.nickname)}</div>`}</header><div class="photoWrap"><img class="photo" src="${safeUrl(payload.property.imageUrl)}"><div class="shade"></div><div class="location">${escape(payload.property.location)}</div><div class="code">${escape(payload.property.code)}</div></div><div class="body"><h1 class="title">${escape(payload.property.title)}</h1>${payload.copy.headline ? `<p class="headline">${escape(payload.copy.headline)}</p>` : ""}${payload.copy.supportingText ? `<p class="support">${escape(payload.copy.supportingText)}</p>` : ""}<div class="facts">${payload.property.stats.map((item) => `<div class="fact">${statIcon(item.kind)}<div><div class="factValue">${escape(item.value)}</div><div class="factLabel">${escape(item.label)}</div></div></div>`).join("")}</div><div class="bottom"><div class="price">${escape(payload.property.price)}</div><div class="cta">${escape(payload.copy.cta)}</div></div></div></div></body></html>`;
}
